// SPDX-License-Identifier: AGPL-3.0-only

// Build script for spark-storage:
//   1. Link libcuda for the raw driver FFI in cuda_min.rs.
//   2. Compile predictor CUDA kernels (.cu → .ptx) via nvcc, emit
//      `OUT_DIR/predictor_ptx.rs` so callers can `include!` to obtain the
//      PTX text at compile time.
//
// Honours `ATLAS_SKIP_BUILD=1` (alias `SKIP_ATLAS_BUILD=1`): skip nvcc and
// emit a stub `storage_ptx.rs` with an empty registry. This lets `cargo
// check`, `cargo clippy`, `cargo test`, and `rustdoc` run on hosts
// without a CUDA toolchain — the same convention `crates/atlas-kernels`
// follows. Anything that actually launches a kernel will fail at runtime
// against the empty stub; production builds must keep this var unset.

use std::path::{Path, PathBuf};
use std::process::Command;

const KERNELS: &[&str] = &[
    "q_lowrank_project",
    "kv_lowrank_project",
    "predictor_score",
    "paged_decode_attn_tiled",
    "attention_finalize",
];

fn main() {
    println!("cargo:rerun-if-env-changed=ATLAS_SKIP_BUILD");
    println!("cargo:rerun-if-env-changed=SKIP_ATLAS_BUILD");
    println!("cargo:rerun-if-env-changed=ATLAS_TARGET_HW");
    // FIRST, before any early return: `rustc-check-cfg` does not cross crates,
    // so this crate must declare the cfg name or every `#[cfg(atlas_rdma_verbs)]`
    // below trips `unexpected_cfgs` (a hard error under `warnings = "deny"`).
    println!("cargo:rustc-check-cfg=cfg(atlas_rdma_verbs)");

    // Apple Silicon hosts have no libcuda and no nvcc. Emit the stub and
    // skip the linker hint so `cargo check` works under
    // `--no-default-features --features metal`. Production CUDA builds
    // still link libcuda below.
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os == "macos" {
        emit_stub();
        println!("cargo:rerun-if-changed=build.rs");
        return;
    }

    // libcuda must always be linked — the skip flag only suppresses nvcc
    // PTX compilation, not the rustc linker step. Examples and binaries
    // still call into `cuda_min` / `cuda_module` and need the dynamic
    // symbols resolved at link time even when the kernel registry is
    // an empty stub.
    link_libcuda();
    // The one-sided RDMA verbs shim is built by the CUDA-free `atlas-rdma`
    // crate; `rustc-cfg` does not cross crate boundaries, so re-emit
    // `atlas_rdma_verbs` here for this crate's own gated code, keyed off
    // atlas-rdma's `links` metadata (`cargo:has_verbs=1` → the DEP_ var below,
    // visible because we depend on atlas-rdma DIRECTLY). The ON condition
    // (Linux AND !ATLAS_SKIP_BUILD) is decided in one place — atlas-rdma/build.rs.
    if std::env::var("DEP_ATLAS_RDMA_SHIM_HAS_VERBS").is_ok() {
        println!("cargo:rustc-cfg=atlas_rdma_verbs");
    }
    if skip_build() {
        emit_stub();
        println!("cargo:rerun-if-changed=build.rs");
        return;
    }
    // The native-HIP target (strix-hip) ships hipcc, not nvcc, and these
    // predictor kernels are NVIDIA-PTX loaded as PTX text — porting them to HIP
    // code objects is future work. The windows/amd-hip build is compile-only
    // (hosted runners have no AMD GPU), so emit the empty registry rather than
    // panicking on a missing nvcc. SCALE (`strix`) keeps nvcc — it ships one.
    if std::env::var("ATLAS_TARGET_HW").as_deref() == Ok("strix-hip") {
        emit_stub();
        println!("cargo:rerun-if-changed=build.rs");
        return;
    }
    compile_kernels();
    println!("cargo:rerun-if-changed=build.rs");
}

fn skip_build() -> bool {
    let truthy = |key: &str| {
        matches!(
            std::env::var(key).ok().as_deref(),
            Some("1") | Some("true") | Some("TRUE")
        )
    };
    truthy("ATLAS_SKIP_BUILD") || truthy("SKIP_ATLAS_BUILD")
}

fn emit_stub() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let stub = "// Auto-generated by spark-storage/build.rs (ATLAS_SKIP_BUILD stub).\n\
        pub struct StoragePtx { pub name: &'static str, pub ptx: &'static str }\n\
        pub static STORAGE_PTX: &[StoragePtx] = &[];\n";
    std::fs::write(out_dir.join("storage_ptx.rs"), stub).expect("emit stub storage_ptx.rs");
}

fn link_libcuda() {
    let cuda_lib_dirs = [
        "/usr/local/cuda/targets/sbsa-linux/lib/stubs",
        "/usr/local/cuda/targets/x86_64-linux/lib/stubs",
        "/usr/local/cuda-13.0/targets/sbsa-linux/lib/stubs",
        "/usr/lib/aarch64-linux-gnu",
        "/usr/lib/x86_64-linux-gnu",
    ];
    for dir in cuda_lib_dirs {
        if Path::new(dir).is_dir() {
            println!("cargo:rustc-link-search=native={dir}");
        }
    }
    println!("cargo:rustc-link-lib=dylib=cuda");
}

fn compile_kernels() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let kernels_dir = manifest_dir.join("kernels");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let nvcc = find_nvcc();
    let arch = std::env::var("ATLAS_PREDICTOR_ARCH").unwrap_or_else(|_| "sm_121".into());

    let mut emit = String::new();
    emit.push_str("// Auto-generated by spark-storage/build.rs.\n");
    emit.push_str("pub struct StoragePtx { pub name: &'static str, pub ptx: &'static str }\n");
    emit.push_str("pub static STORAGE_PTX: &[StoragePtx] = &[\n");

    for stem in KERNELS {
        let src = kernels_dir.join(format!("{stem}.cu"));
        let ptx_out = out_dir.join(format!("{stem}.ptx"));
        println!("cargo:rerun-if-changed={}", src.display());
        let status = Command::new(&nvcc)
            .args([
                "--ptx",
                &format!("-arch={arch}"),
                "-O3",
                "--use_fast_math",
                src.to_str().unwrap(),
                "-o",
                ptx_out.to_str().unwrap(),
            ])
            .status()
            .unwrap_or_else(|e| panic!("invoke nvcc ({}): {e}", nvcc.display()));
        if !status.success() {
            panic!("nvcc --ptx failed for {}", src.display());
        }
        // `{:?}` supplies the quotes AND escapes the path: a Windows OUT_DIR
        // like `D:\a\atlas\...` interpolated raw makes `\a` an invalid Rust
        // escape, and the generated storage_ptx.rs fails to lex.
        emit.push_str(&format!(
            "    StoragePtx {{ name: \"{stem}\", ptx: include_str!({}) }},\n",
            format_args!("{:?}", ptx_out.to_string_lossy())
        ));
    }
    emit.push_str("];\n");
    std::fs::write(out_dir.join("storage_ptx.rs"), emit).expect("emit storage_ptx.rs");
}

fn find_nvcc() -> PathBuf {
    let candidates = ["/usr/local/cuda/bin/nvcc", "/usr/local/cuda-13.0/bin/nvcc"];
    for c in candidates {
        if Path::new(c).is_file() {
            return PathBuf::from(c);
        }
    }
    PathBuf::from("nvcc")
}
