// SPDX-License-Identifier: AGPL-3.0-only

//! N-gram embedding id math — LongCat-Flash-Lite / Qwen3.8-Flash-Next family.
//!
//! Host-side, kernel-independent core of the n-gram embedding path (arxiv
//! 2601.21204): the polynomial-rolling-hash ids that select rows in the
//! `K * (N-1)` giant lookup tables. Split from the (future) GPU module so
//! the integer math has a pure unit-test surface — the Rust ids are checked
//! BIT-EXACT against the Python reference via
//! `bench/ngram_ref/ngram_id_fixtures.json` (generated by
//! `bench/ngram_ref/make_fixtures.py` from the line-faithful numpy port of
//! the HF `modeling_longcat_ngram.py`).
//!
//! Mechanism (table `index = (i-2)*K + j` for n-gram size `i`, split `j`):
//!
//! ```text
//!   T      = ratio * vocab_size + 2*index + 1        (table row count)
//!   mods   = [V^1 mod T, V^2 mod T, ..., V^(i-1) mod T]
//!   id_t   = ( x_t + Σ_{d=1..i-1} shift_d(x)_t * mods[d-1] ) mod T
//! ```
//!
//! where `shift_d` is a right-shift by `d` that RESETS at document
//! boundaries: a position within `d` tokens of a segment start (segments
//! end at an EOS token, inclusive) contributes token id 0 instead of
//! crossing the boundary. Ids depend ONLY on token ids — never on hidden
//! state — which is what makes the lookups deterministic, prefetchable and
//! speculative-decode-friendly.
//!
//! Overflow contract: `x * mod < 2^17 * 2^24 < 2^41` and at most N-1 terms
//! accumulate, so the running sum fits comfortably in i64/u64 WITHOUT
//! intermediate reduction at LongCat scale (V=131072, T≈10.2M). The
//! per-term products must still be computed in 64-bit — 32-bit would
//! overflow — and `mods` themselves must be built with 64-bit modmul.

/// The n-gram trio + derived dims, extracted from `ModelConfig`.
#[derive(Debug, Clone, Copy)]
pub struct NgramDims {
    pub vocab_size: u64,
    pub ratio: u64,
    /// Largest n-gram size N (>= 2).
    pub neighbor_num: usize,
    /// Hash splits K per n-gram size.
    pub split_num: usize,
    pub eos_token_id: u32,
    pub hidden_size: usize,
}

impl NgramDims {
    pub fn from_config(c: &atlas_core::config::ModelConfig) -> Option<Self> {
        if c.ngram_vocab_size_ratio == 0 {
            return None;
        }
        Some(Self {
            vocab_size: c.vocab_size as u64,
            ratio: c.ngram_vocab_size_ratio as u64,
            neighbor_num: c.emb_neighbor_num,
            split_num: c.emb_split_num,
            eos_token_id: c.eos_token_id,
            hidden_size: c.hidden_size,
        })
    }

    pub fn num_tables(&self) -> usize {
        self.split_num * (self.neighbor_num - 1)
    }

    /// Per-table embedding dim = hidden / num_tables (validated at parse).
    pub fn table_dim(&self) -> usize {
        self.hidden_size / self.num_tables()
    }

    /// Row count of table `index`: `ratio*vocab + 2*index + 1` — the
    /// consecutive odd offsets give the K tables of one n-gram size
    /// distinct (near-coprime) sizes so a collision in one split is
    /// independent of the others.
    pub fn table_rows(&self, index: usize) -> u64 {
        self.ratio * self.vocab_size + 2 * index as u64 + 1
    }

    /// `[V^1 mod T, ..., V^(i-1) mod T]` for table (i, j).
    pub fn vocab_mods(&self, ngram: usize, split: usize) -> Vec<u64> {
        let index = (ngram - 2) * self.split_num + split;
        let t = self.table_rows(index);
        let mut mods = Vec::with_capacity(ngram - 1);
        let mut power: u64 = 1;
        for _ in 0..ngram - 1 {
            // 64-bit modmul: V < 2^18, power < T < 2^25 → product < 2^43. OK.
            power = (power * self.vocab_size) % t;
            mods.push(power);
        }
        mods
    }
}

/// `shift_right_ignore_eos` over one sequence: out[t] = ctx[t-n] unless the
/// span [t-n, t] crosses a document boundary (EOS-inclusive segment end),
/// in which case 0. Mirrors the reference implementation exactly, including
/// the quirk that a segment shorter than n contributes nothing.
mod embed;
mod ids;
mod table;

pub use embed::NgramEmbedding;
pub use ids::ngram_ids;
pub use table::NgramTable;

#[cfg(test)]
mod tests;
