// SPDX-License-Identifier: AGPL-3.0-only

//! Oracle for the Hopper FP8 activation-quantizer twin (#928, #927).
//!
//! THE GATE IS BITWISE. `kernels/hopper/common/fp8_act_quant_hopper.cu` changes
//! the load width, the CTA's group count and the reduction tree of
//! `per_token_group_quant_fp8` and NOTHING else — same `amax / 448.0f`, same
//! `1e-12f` floor, same per-element `div.rn.f32`, same saturating
//! `__nv_cvt_float_to_fp8`. So "close enough" is the wrong answer: one differing
//! FP8 byte means an expression moved, and every W8A8 projection in the model
//! reads these bytes. Both the FP8 tensor AND the FP32 scale tensor are
//! compared byte for byte; the worst absolute scale difference is printed so a
//! failure is diagnosable, not because a non-zero value would be accepted.
//!
//! SHAPES are the ones round 13's nsys attribution prices: `K` in
//! {5120, 6144, 17408} (hidden, GDN value_dim, FFN intermediate) crossed with
//! `M` in {16, 17, 25, 1168, 4576} — the n=16 decode step, the 17- and
//! 25-token prefill tail chunks, and the two prefill head chunks.
//!
//! GUARD BANDS bracket every device buffer either kernel writes. The twin
//! derives its own K-group span from `gridDim.y`, so a span bug writes PAST the
//! row rather than producing wrong numbers inside it, and a byte comparison of
//! the payload alone would not see it.
//!
//! KNOWN_BAD is a host-side E4M3 encoder with round-to-nearest REMOVED
//! (`e4m3_trunc` below — the gb10 software encoder `scl_enc_fp8` with its
//! rounding terms deleted). It must DIFFER from what the device produced. A
//! bitwise harness that has never once reported a difference is not evidence,
//! and the difference it must find is precisely the class this kernel could
//! introduce.
//!
//! THROUGHPUT is reported per arm on the attribution's byte model —
//! `M*K*(2 read + 1 write) + M*(K/128)*4` of compulsory traffic — so the run
//! answers the question the lever was opened for. It is a single-harness
//! observation on whatever GPU executes it; on a non-Hopper device the twin
//! does not exist and the run says so and exits.
//!
//! Run: `cargo run -p spark-model --features cuda,gpu-examples \
//!        --example native_fp8_act_quant_hopper_microtest`

use anyhow::Result;
use spark_model::layers::ops;
use spark_runtime::cuda_backend::AtlasCudaBackend;
use spark_runtime::gpu::{DevicePtr, GpuBackend, KernelHandle};

const K_DIMS: [u32; 3] = [5120, 6144, 17408];
const M_DIMS: [u32; 5] = [16, 17, 25, 1168, 4576];
const M_MAX: u32 = 4576;
const GROUP: u32 = 128;
const E4M3_MAX: f32 = 448.0;
const GUARD: usize = 256;
const SENTINEL: u8 = 0x5a;
const WARMUP: u32 = 3;
const REPS: u32 = 20;
/// H100 SXM5 HBM3, `kernels/hopper/HARDWARE.toml`.
const HBM_GBPS: f64 = 3350.0;

/// Deterministic LCG. A thread-rng would make a failing byte unreproducible.
struct Lcg(u32);
impl Lcg {
    fn next_bits(&mut self) -> u32 {
        self.0 = self.0.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        self.0
    }
    fn next_unit(&mut self) -> f32 {
        ((self.next_bits() >> 8) & 0xFF_FFFF) as f32 / 8_388_608.0 - 1.0
    }
}

/// One BF16 value, as the two bytes the kernel will read. Generated by
/// TRUNCATING an f32 rather than rounding it, so the host knows the exact value
/// the device sees with no second rounding rule in play.
fn bf16_bits(v: f32) -> u16 {
    (v.to_bits() >> 16) as u16
}
fn bf16_value(b: u16) -> f32 {
    f32::from_bits(u32::from(b) << 16)
}

/// `PATTERN_GROUPS` distinct 128-element groups, tiled across the activation.
///
/// Distinct groups rather than one repeated row: the amax reduction is per
/// group, and a buffer whose groups all share a maximum would pass a broken
/// tree. Tiled rather than fully random because the largest case is 79.6 M
/// elements and a per-element host RNG dominates the run.
///
/// The first four groups are the cases a random draw will not produce:
///   0  all zeros            -> amax 0, the `1e-12f` scale floor
///   1  one huge value       -> every other element quantizes near zero
///   2  exact E4M3 tie points -> round-to-nearest-even must agree
///   3  +/- E4M3 max and past it -> the saturating clamp on both signs
const PATTERN_GROUPS: u32 = 1024;

fn build_pattern(seed: u32) -> Vec<u16> {
    let mut r = Lcg(seed);
    let n = (PATTERN_GROUPS * GROUP) as usize;
    let mut p = vec![0u16; n];
    // Group 0 stays all-zero from the `vec![0u16; n]` above: amax 0, which is
    // the only input that reaches the `1e-12f` scale floor.
    for i in 0..GROUP as usize {
        let g1 = GROUP as usize + i;
        p[g1] = if i == 7 {
            bf16_bits(3.5e4)
        } else {
            bf16_bits(r.next_unit() * 1e-3)
        };
        // Ties: k + 0.5 ulp at E4M3 exponent 0, where round-to-nearest-EVEN
        // and round-half-away differ on every other value.
        let g2 = 2 * GROUP as usize + i;
        p[g2] = bf16_bits((1.0 + (i % 16) as f32 / 16.0) * 0.0625 * ((i % 3) as f32 - 1.0));
        let g3 = 3 * GROUP as usize + i;
        p[g3] = bf16_bits(match i % 4 {
            0 => E4M3_MAX,
            1 => -E4M3_MAX,
            2 => 1.0e6,
            _ => -1.0e6,
        });
    }
    for slot in p.iter_mut().skip(4 * GROUP as usize) {
        // Spread over ~6 decades so different groups land on different scales.
        let mag = 10f32.powi(((r.next_bits() >> 3) % 7) as i32 - 4);
        *slot = bf16_bits(r.next_unit() * mag);
    }
    p
}

/// `M_MAX` rows of `k` BF16 elements, as device-ready bytes. Every shorter M is
/// this buffer's first `m*k` rows, so one host build serves all five.
fn build_rows(pattern: &[u16], k: u32) -> Vec<u8> {
    let mut out = vec![0u8; M_MAX as usize * k as usize * 2];
    for m in 0..M_MAX as usize {
        for i in 0..k as usize {
            let v = pattern[(m * 7 + i) % pattern.len()];
            let o = (m * k as usize + i) * 2;
            out[o..o + 2].copy_from_slice(&v.to_le_bytes());
        }
    }
    out
}

fn guarded(g: &dyn GpuBackend, bytes: usize) -> Result<(DevicePtr, DevicePtr)> {
    let base = g.alloc(bytes + 2 * GUARD)?;
    g.copy_h2d(&vec![SENTINEL; bytes + 2 * GUARD], base)?;
    Ok((base, base.offset(GUARD)))
}

fn guards_intact(g: &dyn GpuBackend, base: DevicePtr, bytes: usize) -> Result<bool> {
    let mut raw = vec![0u8; bytes + 2 * GUARD];
    g.copy_d2h(base, &mut raw)?;
    Ok(raw[..GUARD].iter().all(|b| *b == SENTINEL)
        && raw[GUARD + bytes..].iter().all(|b| *b == SENTINEL))
}

fn dn(g: &dyn GpuBackend, p: DevicePtr, bytes: usize) -> Result<Vec<u8>> {
    let mut b = vec![0u8; bytes];
    g.copy_d2h(p, &mut b)?;
    Ok(b)
}

fn time_us(g: &dyn GpuBackend, mut run: impl FnMut() -> Result<()>) -> Result<f64> {
    for _ in 0..WARMUP {
        run()?;
    }
    g.synchronize(0)?;
    let t0 = std::time::Instant::now();
    for _ in 0..REPS {
        run()?;
    }
    g.synchronize(0)?;
    Ok(t0.elapsed().as_secs_f64() * 1e6 / f64::from(REPS))
}

/// KNOWN_BAD. `kernels/gb10/common/per_token_group_quant_fp8.cu`'s software
/// E4M3 encoder with the two rounding terms (`+ (1 << 19)` on the normal path,
/// `+ 0.5` on the subnormal path) DELETED — i.e. round-toward-zero. Every other
/// line, including the saturation, is the real encoder's.
fn e4m3_trunc(v: f32) -> u8 {
    if v.is_nan() {
        return 0x7F;
    }
    let bb = v.to_bits();
    let sign = (bb >> 31) & 1;
    let e = ((bb >> 23) & 0xFF) as i32 - 127;
    let man = bb & 0x7F_FFFF;
    let mut ee = e + 7;
    let em;
    if ee < 1 {
        ee = 0;
        let a = v.abs();
        em = if e >= -10 {
            ((a / 0.001_953_125).floor() as u32).min(7)
        } else {
            0
        };
    } else if ee > 15 {
        ee = 15;
        em = 6;
    } else {
        em = man >> 20;
    }
    ((sign << 7) | ((ee as u32) << 3) | em) as u8
}

/// Number of differing bytes between two slices, and the first index.
fn first_diff(a: &[u8], b: &[u8]) -> (usize, usize) {
    let mut n = 0usize;
    let mut at = usize::MAX;
    for (i, (x, y)) in a.iter().zip(b.iter()).enumerate() {
        if x != y {
            if at == usize::MAX {
                at = i;
            }
            n += 1;
        }
    }
    (n, at)
}

/// Worst absolute difference between two FP32 tensors, as bytes.
fn worst_f32(a: &[u8], b: &[u8]) -> f64 {
    let mut w = 0.0f64;
    for (x, y) in a.chunks_exact(4).zip(b.chunks_exact(4)) {
        let xv = f64::from(f32::from_le_bytes(x.try_into().unwrap()));
        let yv = f64::from(f32::from_le_bytes(y.try_into().unwrap()));
        w = w.max((xv - yv).abs());
    }
    w
}

struct Arm {
    fp8: Vec<u8>,
    scale: Vec<u8>,
    us: f64,
}

fn run_arm(
    g: &dyn GpuBackend,
    quant: ops::Fp8ActQuant,
    input: DevicePtr,
    m: u32,
    k: u32,
) -> Result<(Arm, bool)> {
    let fp8_bytes = m as usize * k as usize;
    let scale_bytes = m as usize * (k / GROUP) as usize * 4;
    let (fp8_base, fp8) = guarded(g, fp8_bytes)?;
    let (scale_base, scale) = guarded(g, scale_bytes)?;

    let us = time_us(g, || {
        ops::per_token_group_quant_fp8(g, quant, input, fp8, scale, m, k, 0)
    })?;
    g.synchronize(0)?;

    let out = Arm {
        fp8: dn(g, fp8, fp8_bytes)?,
        scale: dn(g, scale, scale_bytes)?,
        us,
    };
    let ok = guards_intact(g, fp8_base, fp8_bytes)? && guards_intact(g, scale_base, scale_bytes)?;
    g.free(fp8_base).ok();
    g.free(scale_base).ok();
    Ok((out, ok))
}

/// Compulsory traffic of one launch, on the attribution's model: read the BF16
/// activation once, write the FP8 bytes once, write the FP32 scales once.
fn gbps(m: u32, k: u32, us: f64) -> f64 {
    let bytes = m as f64 * k as f64 * 3.0 + m as f64 * (k / GROUP) as f64 * 4.0;
    bytes / (us * 1e-6) / 1e9
}

fn leg(
    g: &dyn GpuBackend,
    shared: ops::Fp8ActQuant,
    hopper: ops::Fp8ActQuant,
    host_rows: &[u8],
    input: DevicePtr,
    m: u32,
    k: u32,
) -> Result<()> {
    g.copy_h2d(&host_rows[..m as usize * k as usize * 2], input)?;

    let (a, a_ok) = run_arm(g, shared, input, m, k)?;
    let (b, b_ok) = run_arm(g, hopper, input, m, k)?;

    let (fp8_n, fp8_at) = first_diff(&a.fp8, &b.fp8);
    let (sc_n, sc_at) = first_diff(&a.scale, &b.scale);

    eprintln!(
        "  M={m:<5} K={k:<6} shared {:8.2} us ({:6.1} GB/s, {:4.1}% HBM)  \
         hopper {:8.2} us ({:6.1} GB/s, {:4.1}% HBM)  speedup {:.2}x",
        a.us,
        gbps(m, k, a.us),
        gbps(m, k, a.us) / HBM_GBPS * 100.0,
        b.us,
        gbps(m, k, b.us),
        gbps(m, k, b.us) / HBM_GBPS * 100.0,
        a.us / b.us,
    );

    anyhow::ensure!(a_ok, "M={m} K={k}: the shared kernel wrote past its buffer");
    anyhow::ensure!(b_ok, "M={m} K={k}: the Hopper twin wrote past its buffer");
    anyhow::ensure!(
        fp8_n == 0,
        "M={m} K={k}: {fp8_n} FP8 bytes differ (first at {fp8_at}); the twin must be \
         BIT-identical to `per_token_group_quant_fp8`"
    );
    anyhow::ensure!(
        sc_n == 0,
        "M={m} K={k}: {sc_n} scale bytes differ (first at {sc_at}, worst abs {:.3e})",
        worst_f32(&a.scale, &b.scale)
    );

    // KNOWN_BAD: the same input and the SAME device scales, re-encoded with
    // round-toward-zero. It must differ, or the byte comparison above proves
    // nothing about rounding. Row 0 only — one row is 5120..17408 elements,
    // which is thousands of independent chances to round differently.
    let mut bad = 0usize;
    for i in 0..k as usize {
        let scale = f32::from_le_bytes(
            b.scale[(i / GROUP as usize) * 4..(i / GROUP as usize) * 4 + 4]
                .try_into()
                .unwrap(),
        );
        let v = bf16_value(u16::from_le_bytes(
            host_rows[i * 2..i * 2 + 2].try_into().unwrap(),
        ));
        let q = (v / scale).clamp(-E4M3_MAX, E4M3_MAX);
        if e4m3_trunc(q) != b.fp8[i] {
            bad += 1;
        }
    }
    anyhow::ensure!(
        bad > 0,
        "M={m} K={k}: KNOWN_BAD (round-toward-zero) matched the kernel on every byte of \
         row 0 — this harness cannot see a rounding change and its PASS means nothing"
    );
    Ok(())
}

fn main() -> Result<()> {
    let backend = AtlasCudaBackend::new(0, &atlas_kernels::ptx_modules())?;
    let g: &dyn GpuBackend = &backend;

    let resolved = ops::Fp8ActQuant::resolve(g);
    anyhow::ensure!(
        resolved.shared.0 != 0,
        "`per_token_group_quant_fp8` is not in this image; nothing to compare against"
    );
    anyhow::ensure!(
        resolved.hopper.0 != 0,
        "`fp8_act_quant_hopper::per_token_group_quant_fp8_hopper` is not in this image — \
         this microtest is for a build of `kernels/hopper`"
    );
    let shared = ops::Fp8ActQuant::shared_only(resolved.shared);
    let hopper = ops::Fp8ActQuant {
        shared: KernelHandle(0),
        hopper: resolved.hopper,
    };

    eprintln!(
        "native_fp8_act_quant_hopper_microtest: groups/CTA={} HBM={HBM_GBPS} GB/s",
        ops::FP8_QUANT_HOPPER_GROUPS_PER_CTA
    );
    let pattern = build_pattern(0x5EED_1234);
    for k in K_DIMS {
        let rows = build_rows(&pattern, k);
        let input = g.alloc(M_MAX as usize * k as usize * 2)?;
        for m in M_DIMS {
            leg(g, shared, hopper, &rows, input, m, k)?;
        }
        g.free(input).ok();
    }
    eprintln!("  ALL LEGS BIT-IDENTICAL (fp8 bytes and fp32 scales), KNOWN_BAD fired on each");
    Ok(())
}
