// SPDX-License-Identifier: AGPL-3.0-only
//
// Codegen + nvcc-discovery helpers for build.rs. Included via
// `#[path = "build_codegen.rs"] mod build_codegen;` so types from build.rs
// (`Target`) are reachable via `super::`.

use std::env;
use std::path::PathBuf;

use super::{SamplingCat, Target};

/// Generate the target_ptx.rs source with per-target kernel constants and
/// lookup functions.
///
/// Kernel blobs are emitted uniformly as `&'static [u8]` via
/// `include_bytes!` — NVIDIA PTX is ASCII text but is still valid as
/// bytes, while SCALE/AMD (gfx1151) and Metal produce binary objects.
/// The runtime (`AtlasRegistry`) detects text-vs-binary per blob.
///
/// `cuda_api` is true for backends that load kernels via the CUDA module
/// API (NVIDIA, SCALE, HIP) — for those the real `all_ptx_sets()` registry
/// is generated. Metal sets it false and gets a type-checking stub
/// (Metal consumers read `metallib_modules()`).
pub(super) fn generate_target_ptx_rs(
    targets: &[Target],
    all_modules: &[Vec<(String, String)>],
    all_drops: &[Vec<(String, String)>],
    output_ext: &str,
    cuda_api: bool,
) -> String {
    let mut g = String::new();
    g.push_str("// Auto-generated by build.rs — do not edit.\n");
    g.push_str("// KernelTarget and TargetPtxSet are imported by the parent lib.rs.\n\n");

    // Kernel blobs are emitted uniformly as `&[u8]` (`include_bytes!`):
    // PTX text is valid as bytes, AMD/Metal objects are binary, and one
    // representation lets `all_ptx_sets()` work for every backend.
    // `const_ty` drops the `'static` (consts default to `'static` —
    // clippy::redundant_static_lifetimes); `modules_ty` keeps it (no
    // elision possible for a function return signature).
    let const_suffix = "KERNEL";
    let const_ty = "&[u8]";
    let include_macro = "include_bytes!";
    let fn_root = "ptx_modules";
    let modules_ty = "Vec<(&'static str, &'static [u8])>";

    let single_target = targets.len() == 1;

    for (idx, (target, modules)) in targets.iter().zip(all_modules.iter()).enumerate() {
        let prefix = if single_target {
            String::new()
        } else {
            format!("T{idx}_")
        };

        // Kernel-blob constants
        for (stem, module_name) in modules {
            let const_name = format!("{}{}_{}", prefix, module_name.to_uppercase(), const_suffix);
            g.push_str(&format!(
                "pub const {const_name}: {const_ty} = \
                 {include_macro}(concat!(env!(\"ATLAS_PTX_DIR\"), \"/t{idx}__{stem}.{output_ext}\"));\n"
            ));
        }
        g.push('\n');

        // Per-target lookup function
        let fn_name = if single_target {
            fn_root.to_string()
        } else {
            format!("{fn_root}_t{idx}")
        };
        g.push_str(&format!(
            "/// Kernel modules for target: ({}, {}, {}).\n",
            target.hw, target.model, target.quant
        ));
        g.push_str(&format!(
            "pub fn {fn_name}() -> {modules_ty} {{\n    vec![\n"
        ));
        for (_, module_name) in modules {
            let const_name = format!("{}{}_{}", prefix, module_name.to_uppercase(), const_suffix);
            g.push_str(&format!("        (\"{module_name}\", {const_name}),\n"));
        }
        g.push_str("    ]\n}\n\n");
    }

    // Multi-target builds: `ptx_modules()` aliases the first target.
    if !single_target {
        g.push_str(
            "/// Kernel modules for the default (first) target.\n\
             ///\n\
             /// Backward-compatible alias. Prefer `all_ptx_sets()` for multi-target builds.\n\
             pub fn ptx_modules() -> Vec<(&'static str, &'static [u8])> {\n\
             \x20   ptx_modules_t0()\n\
             }\n\n",
        );
    }

    // `metallib_modules()` — the same blob list under the Metal-side
    // name so metal-feature consumers keep compiling. Blobs are uniform
    // `&[u8]`, so this is a plain alias of `ptx_modules()`.
    g.push_str(
        "/// Alias of `ptx_modules()` for Metal-feature consumers.\n\
         pub fn metallib_modules() -> Vec<(&'static str, &'static [u8])> {\n\
         \x20   ptx_modules()\n\
         }\n\n",
    );

    // Non-CUDA backends (Metal) have their own registry path; emit an
    // empty `all_ptx_sets()` so the shared surface still type-checks.
    if !cuda_api {
        g.push_str(
            "/// Empty registry stub — this build targets a non-CUDA backend.\n\
             pub fn all_ptx_sets() -> Vec<TargetPtxSet> { Vec::new() }\n",
        );
        return g;
    }

    // all_ptx_sets() function — always generated for cuda targets
    g.push_str(
        "/// All compiled kernel targets and their PTX module sets.\n\
         pub fn all_ptx_sets() -> Vec<TargetPtxSet> {\n\
         \x20   vec![\n",
    );
    for (idx, target) in targets.iter().enumerate() {
        // Strip trailing 'f' from arch for KernelTarget (sm_121f → sm_121)
        let arch_clean = target.arch.trim_end_matches('f');
        let fn_name = if single_target {
            "ptx_modules".to_string()
        } else {
            format!("ptx_modules_t{idx}")
        };
        let fmt_cat = |c: &SamplingCat| -> String {
            format!(
                "SamplingCategory {{ temperature: {:.2}, top_p: {:.2}, top_k: {}, presence_penalty: {:.2}, frequency_penalty: {:.2}, repetition_penalty: {:.2}, dry_multiplier: {:.2}, dry_base: {:.2}, dry_allowed_length: {}, lz_penalty: {:.2}, min_p: {}, top_n_sigma: {} }}",
                c.temperature,
                c.top_p,
                c.top_k,
                c.presence_penalty,
                c.frequency_penalty,
                c.repetition_penalty,
                c.dry_multiplier,
                c.dry_base,
                c.dry_allowed_length,
                c.lz_penalty,
                match c.min_p {
                    Some(v) => format!("Some({v:.4})"),
                    None => "None".to_string(),
                },
                match c.top_n_sigma {
                    Some(v) => format!("Some({v:.4})"),
                    None => "None".to_string(),
                },
            )
        };
        g.push_str(&format!(
            "        TargetPtxSet {{\n\
             \x20           target: KernelTarget {{ arch: \"{arch_clean}\", model: \"{}\", quant: \"{}\" }},\n\
             \x20           modules: {fn_name}(),\n\
             \x20           sampling: SamplingPresets {{\n\
             \x20               thinking_text: {},\n\
             \x20               thinking_coding: {},\n\
             \x20               non_thinking: {},\n\
             \x20               tools: {},\n\
             \x20           }},\n\
             \x20           behavior: ModelBehavior {{\n\
             \x20               thinking_in_tools: {},\n\
             \x20               max_thinking_budget: {},\n\
             \x20               effort_capped_at_ceiling: {},\n\
             \x20               thinking_default: {},\n\
             \x20               fp8_kv_calibration_tokens: {},\n\
             \x20               default_kv_dtype: \"{}\",\n\
             \x20               default_num_drafts: {},\n\
             \x20               disable_tool_steering: {},\n\
             \x20               disable_cwd_hint_injection: {},\n\
             \x20               use_sampling_presets_for_core: {},\n\
             \x20               tool_call_parser: \"{}\",\n\
             \x20               enable_loop_watchdog: {},\n\
             \x20               enable_think_loop_watchdog: {},\n\
             \x20               honor_eos_inside_thinking: {},\n\
             \x20               cap_thinking_at_max_tokens: {},\n\
             \x20               min_p_floor: {:?},\n\
             \x20               min_reasoning_floor_tokens: {},\n\
             \x20               temperature_max: {:?},\n\
             \x20               think_loop_min_repeats: {},\n\
             \x20               think_loop_scan_window: {},\n\
             \x20               confidence_early_stop: {},\n\
             \x20               confidence_run_length: {},\n\
             \x20               fuzzy_repeat_tolerance_div: {},\n\
             \x20               max_inter_tool_prose: {},\n\
             \x20               max_post_think_content_tokens: {},\n\
             \x20               tscg: {},\n\
             \x20               disable_tool_grammar: {},\n\
             \x20               rollback_resteer: {},\n\
             \x20               rom_head: \"{}\",\n\
             \x20               tool_retry: {},\n\
             \x20               preserve_thinking: {:?},\n\
             \x20           }},\n\
             \x20           model_type_matches: vec![{}],\n\
             \x20           match_names: &[{}],\n\
             \x20           dflash: {},\n\
             \x20           shadowed_dropped: &[{}],\n\
             \x20           expected_absent: &[{}],\n\
             \x20       }},\n",
            target.model, target.quant,
            fmt_cat(&target.sampling_thinking_text),
            fmt_cat(&target.sampling_thinking_coding),
            fmt_cat(&target.sampling_non_thinking),
            fmt_cat(&target.sampling_tools),
            target.behavior_thinking_in_tools,
            target.behavior_max_thinking_budget,
            target.behavior_effort_capped_at_ceiling,
            target.behavior_thinking_default,
            target.behavior_fp8_kv_calibration_tokens,
            target.behavior_default_kv_dtype,
            target.behavior_default_num_drafts,
            target.behavior_disable_tool_steering,
            target.behavior_disable_cwd_hint_injection,
            target.behavior_use_sampling_presets_for_core,
            target.behavior_tool_call_parser,
            target.behavior_enable_loop_watchdog,
            target.behavior_enable_think_loop_watchdog,
            target.behavior_honor_eos_inside_thinking,
            target.behavior_cap_thinking_at_max_tokens,
            target.behavior_min_p_floor,
            target.behavior_min_reasoning_floor_tokens,
            target.behavior_temperature_max,
            target.behavior_think_loop_min_repeats,
            target.behavior_think_loop_scan_window,
            target.behavior_confidence_early_stop,
            target.behavior_confidence_run_length,
            target.behavior_fuzzy_repeat_tolerance_div,
            target.behavior_max_inter_tool_prose,
            target.behavior_max_post_think_content_tokens,
            target.behavior_tscg,
            target.behavior_disable_tool_grammar,
            target.behavior_rollback_resteer,
            target.behavior_rom_head,
            target.behavior_tool_retry,
            target.behavior_preserve_thinking,
            target.model_type_matches.iter().map(|m| {
                let hs = match m.hidden_size {
                    Some(v) => format!("Some({v})"),
                    None => "None".to_string(),
                };
                format!("ModelTypeMatch {{ model_type: \"{}\", hidden_size: {hs} }}", m.model_type)
            }).collect::<Vec<_>>().join(", "),
            target.match_names
                .iter()
                .map(|n| format!("\"{n}\""))
                .collect::<Vec<_>>()
                .join(", "),
            match &target.dflash {
                None => "None".to_string(),
                Some(d) => format!(
                    "Some(DflashConfig {{ draft_model: \"{}\", gamma: {}, window_size: {}, mask_token_id: {}, target_layer_ids: &[{}] }})",
                    d.draft_model, d.gamma, d.window_size, d.mask_token_id,
                    d.target_layer_ids.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                ),
            },
            all_drops
                .get(idx)
                .map(|d| {
                    d.iter()
                        .map(|(m, f)| format!("(\"{m}\", \"{f}\")"))
                        .collect::<Vec<_>>()
                        .join(", ")
                })
                .unwrap_or_default(),
            target
                .expected_absent
                .iter()
                .map(|(m, f)| format!("(\"{m}\", \"{f}\")"))
                .collect::<Vec<_>>()
                .join(", "),
        ));
    }
    g.push_str("    ]\n}\n");

    g
}

/// Locate the SCALE (scale-lang.com) install root for the AMD/`scale`
/// vendor path. A SCALE root is the extracted `scale-<ver>-Linux` dir that
/// contains `bin/scaleenv` and a `targets/` dir (per-arch toolchains).
///
/// Resolution order: `$SCALE_HOME` / `$SCALE_ROOT` (exact root), then a
/// short list of conventional locations, then a shallow scan of `$HOME`
/// and `/opt` for a `scale*-Linux` child. Fails fast (PCND) — no silent
/// default — since an AMD build is meaningless without SCALE.
pub(super) fn find_scale_dir() -> PathBuf {
    let is_scale_root =
        |p: &PathBuf| -> bool { p.join("bin/scaleenv").exists() && p.join("targets").is_dir() };

    for var in ["SCALE_HOME", "SCALE_ROOT"] {
        if let Ok(v) = env::var(var) {
            let p = PathBuf::from(&v);
            if is_scale_root(&p) {
                return p;
            }
            panic!(
                "${var}={v} is not a SCALE install root \
                 (expected bin/scaleenv + targets/)."
            );
        }
    }

    let home = env::var("HOME").unwrap_or_default();
    let mut candidates: Vec<PathBuf> = vec![
        PathBuf::from(&home).join("scale17/scale-1.7.0-Linux"),
        PathBuf::from(&home).join("scale/scale-1.7.0-Linux"),
        PathBuf::from("/opt/scale/scale-1.7.0-Linux"),
        PathBuf::from("/opt/scale"),
    ];
    // Shallow scan: a `scale*-Linux` dir directly under $HOME, ~/scale*,
    // or /opt (covers version drift without hardcoding the version).
    for base in [PathBuf::from(&home), PathBuf::from("/opt")] {
        if let Ok(rd) = std::fs::read_dir(&base) {
            for e in rd.flatten() {
                let p = e.path();
                if p.is_dir() {
                    let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
                    if name.starts_with("scale") {
                        candidates.push(p.clone());
                        // one level down: ~/scaleNN/scale-<ver>-Linux
                        if let Ok(inner) = std::fs::read_dir(&p) {
                            for ie in inner.flatten() {
                                let ip = ie.path();
                                if ip.is_dir()
                                    && ip
                                        .file_name()
                                        .and_then(|n| n.to_str())
                                        .map(|n| n.starts_with("scale"))
                                        .unwrap_or(false)
                                {
                                    candidates.push(ip);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    for c in &candidates {
        if is_scale_root(c) {
            return c.clone();
        }
    }
    panic!(
        "SCALE not found. Set $SCALE_HOME to the scale-<ver>-Linux install \
         root (containing bin/scaleenv + targets/), or install SCALE from \
         scale-lang.com. Searched: {candidates:?}"
    );
}

pub(super) fn find_cuda_dir() -> PathBuf {
    if let Ok(cuda_home) = env::var("CUDA_HOME") {
        return PathBuf::from(cuda_home);
    }
    for path in &[
        "/usr/local/cuda",
        "/usr/local/cuda-13.0",
        "/usr/local/cuda-13",
    ] {
        let p = PathBuf::from(path);
        if p.join("bin/nvcc").exists() {
            return p;
        }
    }
    panic!("CUDA not found. Set CUDA_HOME or install CUDA toolkit.");
}
